server {
    listen 80;
    server_name localhost;

    root /var/www/client/dist;
    index index.html;

    charset utf-8;
    client_max_body_size 50M;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location ^~ /api {
        root /var/www/public;
        try_files $uri $uri/ /index.php?$query_string;

        location ~ \.php$ {
            fastcgi_pass app:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME /var/www/public/index.php;
            include fastcgi_params;
            fastcgi_buffering off;
        }
    }

    location ^~ /storage {
        alias /var/www/storage/app/public;
        try_files $uri $uri/ =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ /\.ht {
        deny all;
    }
}
